# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#Agencias
Agency.create(name: 'Araçá')
Agency.create(name: 'Central')
Agency.create(name: 'Itaquera')
Agency.create(name: 'Lapa')
Agency.create(name: 'Qta. Parada')
Agency.create(name: 'Santana')
Agency.create(name: 'Sto. Amaro')
Agency.create(name: 'Saudade')
Agency.create(name: 'Servidor Municipal')
Agency.create(name: 'Vila Formosa')


#Cemiterios e Crematorios
Cemetery.create(name: 'Alphacampus')
Cemetery.create(name: 'Alvaro Quinteiro Vieira')
Cemetery.create(name: 'Araçá')
Cemetery.create(name: 'Areas Verdes')
Cemetery.create(name: 'Bairro dos Casa (Municipal)')
Cemetery.create(name: 'Bela Vista')
Cemetery.create(name: 'Campo Grande')
Cemetery.create(name: 'Campo Santo')
Cemetery.create(name: 'Cantareira')
Cemetery.create(name: 'Carmo')
Cemetery.create(name: 'Cerejeiras')
Cemetery.create(name: 'Cidade Ariston')
Cemetery.create(name: 'Colonia')
Cemetery.create(name: 'Concessões')
Cemetery.create(name: 'Congonhas')
Cemetery.create(name: 'Consolação')
Cemetery.create(name: 'Crematorio')
Cemetery.create(name: 'Crematorio Horto da Paz')
Cemetery.create(name: 'Crematorio Memorial')
Cemetery.create(name: 'Crematorio Memorial Paulista')
Cemetery.create(name: 'Crematorio Metropolitano')
Cemetery.create(name: 'Cristo Redentor (Vila Pires) - Municipal')
Cemetery.create(name: 'Cristo Rei')
Cemetery.create(name: 'Curuça (Municipal)')
Cemetery.create(name: 'Central Velho de Cotia')
Cemetery.create(name: 'Da Paz')
Cemetery.create(name: 'Das Lagrimas')
Cemetery.create(name: 'Dom Bosco')
Cemetery.create(name: 'Freguesia do Ó')
Cemetery.create(name: 'Gethsemani Anhanguera')
Cemetery.create(name: 'Gethsemani')
Cemetery.create(name: 'Horto da Paz')
Cemetery.create(name: 'Israelita (Butanta)')
Cemetery.create(name: 'Israelita (Vila Mariana)')
Cemetery.create(name: 'Itaquera')
Cemetery.create(name: 'Jardim da Paz')
Cemetery.create(name: 'Jardim das Colina')
Cemetery.create(name: 'Jardim dos Jesuítas')
Cemetery.create(name: 'Jd. Horto Florestal')
Cemetery.create(name: 'Jardim Serra')
Cemetery.create(name: 'Jardim Santa Lidia')
Cemetery.create(name: 'Jardim Vale da Paz')
Cemetery.create(name: 'Lageado - Guaianazes')
Cemetery.create(name: 'Lajeado')
Cemetery.create(name: 'Lapa')
Cemetery.create(name: 'Morumbi')
Cemetery.create(name: 'Municipal de Aruja I')
Cemetery.create(name: 'Municipal de Aruja II')
Cemetery.create(name: 'Municipal de Diadema')
Cemetery.create(name: 'Municipal Jd. das Flores')
Cemetery.create(name: 'Municipal de Santo Andre')
Cemetery.create(name: 'Municipal São Jose')
Cemetery.create(name: 'Nossa Senhora do Bom Sucesso')
Cemetery.create(name: 'Nossa Senhora da Ressurreiçao')
Cemetery.create(name: 'Nossa Senhora das Vitorias')
Cemetery.create(name: 'Ordem 3ª de Nossa Sra do Carmo')
Cemetery.create(name: 'Parelheiros')
Cemetery.create(name: 'Penha')
Cemetery.create(name: 'Phoenix Memorial')
Cemetery.create(name: 'Parque da Cantareira')
Cemetery.create(name: 'Parque das Cerejeiras')
Cemetery.create(name: 'Parque das Garças')
Cemetery.create(name: 'Parque do Cambiri')
Cemetery.create(name: 'Parque dos Girassois - Oasco')
Cemetery.create(name: 'Parque dos Girassois - Parelheiros')
Cemetery.create(name: 'Parque dos Pinheiros')
Cemetery.create(name: 'Parque Jaragua')
Cemetery.create(name: 'Parque Jardim das Primaveras I')
Cemetery.create(name: 'Parque Jardim das Primaveras II')
Cemetery.create(name: 'Parque Vale dos Pinheiros')
Cemetery.create(name: 'Protestantes')
Cemetery.create(name: 'Quarta Parada')
Cemetery.create(name: 'Redentor')
Cemetery.create(name: 'Rosario')
Cemetery.create(name: 'Sagrado Coraçao(Camilopolis) - Municipal')
Cemetery.create(name: 'Santana')
Cemetery.create(name: 'Santissimo Sacramento')
Cemetery.create(name: 'Santissimo Sacrameno')
Cemetery.create(name: 'Sao Luis')
Cemetery.create(name: 'Sao Paulo')
Cemetery.create(name: 'Sao Pedro')
Cemetery.create(name: 'Saudade')
Cemetery.create(name: 'Saudade - Ferraz')
Cemetery.create(name: 'Saudade - Sao Caetano')
Cemetery.create(name: 'Saudade - Taboao da Serra')
Cemetery.create(name: 'Sao Benedito - Biritiba Mirim')
Cemetery.create(name: 'Sao Benedito - Guararema')
Cemetery.create(name: 'Sao Benedito - Santa Isabel')
Cemetery.create(name: 'Sao Joao Batista')
Cemetery.create(name: 'Sao Jose')
Cemetery.create(name: 'Sao Judas Tadeu')
Cemetery.create(name: 'Sao Miguel Arcanjo')
Cemetery.create(name: 'Sao Salvador')
Cemetery.create(name: 'Sao Sebastiao')
Cemetery.create(name: 'Santa Paula')
Cemetery.create(name: 'Santo Amaro')
Cemetery.create(name: 'Santo Antonio')
Cemetery.create(name: 'Tremembe')
Cemetery.create(name: 'Vila Assumpçao')
Cemetery.create(name: 'Vila Baeta Neves')
Cemetery.create(name: 'Vila Euclides (Municípal)')
Cemetery.create(name: 'Vila Formosa')
Cemetery.create(name: 'Vila Formosa II')
Cemetery.create(name: 'Vila Mariana')
Cemetery.create(name: 'Vila Nova Cachoeirinha')
Cemetery.create(name: 'Vila Pauliceia')
Cemetery.create(name: 'Vila Rio')

#Locais de Falecimento
Placeofdeath.create(name: ' Residência Própria ')
Placeofdeath.create(name: ' IML ')
Placeofdeath.create(name: ' SVO ')
Placeofdeath.create(name: ' Abrigo De Velhos  F. Ozanam ')
Placeofdeath.create(name: ' Acemi - Serv. Medico De Parada De Taipas  ')
Placeofdeath.create(name: ' Ama - Pq. Figueira Grande ')
Placeofdeath.create(name: ' Ama Jd Paulistano - Z. Oeste  ')
Placeofdeath.create(name: ' Ama Paraisopolis  ')
Placeofdeath.create(name: ' Ama Parelheiros ')
Placeofdeath.create(name: ' Ambulatorio Angelica  ')
Placeofdeath.create(name: ' Ambulatorio Medico Sao Mateus ')
Placeofdeath.create(name: ' Ambulatorio Sao Vicente De Paula  ')
Placeofdeath.create(name: ' Ambulatorio Saude Mental  ')
Placeofdeath.create(name: ' Ambulatorio Sta Cruz  ')
Placeofdeath.create(name: ' Ambulatorio Do Hosp. E Matern. Sta  Terezinha ')
Placeofdeath.create(name: ' Ambulatorio Da Creche Santa Luzia ')
Placeofdeath.create(name: ' Asilo Sao Vicente De Paula  ')
Placeofdeath.create(name: ' Assoc. Da 3. Idade Cristina ')
Placeofdeath.create(name: ' Assist. Medica Delfim Verde ')
Placeofdeath.create(name: ' Assoc. Matern. De Sao Paulo ')
Placeofdeath.create(name: ' Assoc. Benef . N.Sra De Nazare  ')
Placeofdeath.create(name: ' Assoc. Assist. Mutua A Saude - Sbc  ')
Placeofdeath.create(name: ' Assoc. Filhas De Sao Camilo ')
Placeofdeath.create(name: ' Assoc. Assist. Lar Da Vovo Marrazzi ')
Placeofdeath.create(name: ' Casa De Repouso Cantinho Da Feliz Idade ')
Placeofdeath.create(name: ' Casa De Apoio Liberdade ')
Placeofdeath.create(name: ' Casa De Repouso Coraçao De Jesus  ')
Placeofdeath.create(name: ' Casa De Repouso Flor Do Ipe ')
Placeofdeath.create(name: ' Casa De Repouso Palmeiras ')
Placeofdeath.create(name: ' Casa De Repouso Cidade Vargas ')
Placeofdeath.create(name: ' Centro Comunitario Santana  ')
Placeofdeath.create(name: ' Casa De Cuidados Cantareira ')
Placeofdeath.create(name: ' Centro De Assistencia Medica  ')
Placeofdeath.create(name: ' Centro De Cardiologia De Sao Paulo  ')
Placeofdeath.create(name: ' Centro Especializado De Medicina Avançada ')
Placeofdeath.create(name: ' Centro Homeopatico - Luiz Lustosa De Lima ')
Placeofdeath.create(name: ' Centro Homeopatico - Dr. Silverio C. Pimenta  ')
Placeofdeath.create(name: ' Centro Medico Ajax Walter - Periperi  ')
Placeofdeath.create(name: ' Centro Medico Ameno ')
Placeofdeath.create(name: ' Centro Medico Cantareira  ')
Placeofdeath.create(name: ' Centro Medico Chamberlain ')
Placeofdeath.create(name: ' Centro Medico Moderno ')
Placeofdeath.create(name: ' Centro De Referencia E Treinamento  ')
Placeofdeath.create(name: ' Centro De Saude Do Estado ')
Placeofdeath.create(name: ' Centro Integrado De Atendimento Ao Idoso - Morumbi  ')
Placeofdeath.create(name: ' Clinica Anglo Saude ')
Placeofdeath.create(name: ' Clinica Aproclin  ')
Placeofdeath.create(name: ' Clinica Baruel  ')
Placeofdeath.create(name: ' Clinica De Repouso Est. Da Cantareira ')
Placeofdeath.create(name: ' Clinica Casa Branca ')
Placeofdeath.create(name: ' Clinica Medica Charcot  ')
Placeofdeath.create(name: ' Clinica Climetal  ')
Placeofdeath.create(name: ' Clinica Dia E Noite ')
Placeofdeath.create(name: ' Clinica Da Faculdade De Medicina  ')
Placeofdeath.create(name: ' Clinica Fenix ')
Placeofdeath.create(name: ' Clinica De  Fraturas Da Lapa  ')
Placeofdeath.create(name: ' Clinica Geriatr. Dom Joao Toniolo ')
Placeofdeath.create(name: ' Clinica Geront. Cantinho Do Ceu ')
Placeofdeath.create(name: ' Clinica Central De Guaianazes ')
Placeofdeath.create(name: ' Clinica Placeofdeathar  ')
Placeofdeath.create(name: ' Clinica Iguatemi  ')
Placeofdeath.create(name: ' Clinica Indiana ')
Placeofdeath.create(name: ' Clinica Infantil De Sao Miguel Paulista ')
Placeofdeath.create(name: ' Clinica Integrada Pro-Bem ')
Placeofdeath.create(name: ' Clinica Medica Jd Niteroi ')
Placeofdeath.create(name: ' Clinica Joao Xxiii  ')
Placeofdeath.create(name: ' Clinica De Repouso Leao Dourado ')
Placeofdeath.create(name: ' Clinica Medica Maio ')
Placeofdeath.create(name: ' Clinica Marcone ')
Placeofdeath.create(name: ' Clinica Medica Mediplan ')
Placeofdeath.create(name: ' Clinica Medica Niveal ')
Placeofdeath.create(name: ' Clinica De Repouso N. Sra De Fatima ')
Placeofdeath.create(name: ' Clinica Medica N. Sra De Lourdes  ')
Placeofdeath.create(name: ' Clinica Opan  ')
Placeofdeath.create(name: ' Clinica Oswaldo Cruz  ')
Placeofdeath.create(name: ' Clinica Particular - Unid. I, Ii E Iii  ')
Placeofdeath.create(name: ' Clinica Medica Pirituba ')
Placeofdeath.create(name: ' Clinica De Repouso Pq. Julieta  ')
Placeofdeath.create(name: ' Clinica Pro-Idoso ')
Placeofdeath.create(name: ' Clinica De Repouso Butanta  ')
Placeofdeath.create(name: ' Clinica De Repouso Florestal  ')
Placeofdeath.create(name: ' Clinica De Repouso Interlagos ')
Placeofdeath.create(name: ' Clinica De Repouso Rio Bonito ')
Placeofdeath.create(name: ' Clinica Saint Marie(Morumbi)  ')
Placeofdeath.create(name: ' Clinica Saint Marie(Brooklin) ')
Placeofdeath.create(name: ' Clinica Sao Bento ')
Placeofdeath.create(name: ' Clinica Sao Judas Tadeu ')
Placeofdeath.create(name: ' Clinica Sta Amalia  ')
Placeofdeath.create(name: ' Clinica Medica Sta Cruz ')
Placeofdeath.create(name: ' Clinica Sta Julia ')
Placeofdeath.create(name: ' Clinica Sta Monica  ')
Placeofdeath.create(name: ' Clinica Medica Talita ')
Placeofdeath.create(name: ' Clinica Nova Iguatemi ')
Placeofdeath.create(name: ' Casa De Repouso Cora Coralina ')
Placeofdeath.create(name: ' Casa De Repouso Azalea  ')
Placeofdeath.create(name: ' Casa De Repouso Adonay  ')
Placeofdeath.create(name: ' Casa De Repouso Ana Nery  ')
Placeofdeath.create(name: ' Casa De Repouso Bonfiglioli ')
Placeofdeath.create(name: ' Casa De Repouso Bons Amigos ')
Placeofdeath.create(name: ' Casa De Repouso Cantinho Da Vovo  ')
Placeofdeath.create(name: ' Casa De Repouso Genesys ')
Placeofdeath.create(name: ' Casa De Repouso Giorne Felice ')
Placeofdeath.create(name: ' Casa De Repouso Imperio Dos Anjos ')
Placeofdeath.create(name: ' Casa De Repouso Mansao Dourada  ')
Placeofdeath.create(name: ' Casa De Repouso Maria Zelia ')
Placeofdeath.create(name: ' Casa De Repouso Menotti Parolari  ')
Placeofdeath.create(name: ' Casa De Repouso Moema ')
Placeofdeath.create(name: ' Casa De Repouso Morumbi ')
Placeofdeath.create(name: ' Casa De Repouso Paraiso ')
Placeofdeath.create(name: ' Casa De Repouso Particular  ')
Placeofdeath.create(name: ' Casa De Repouso Raposo Tavares  ')
Placeofdeath.create(name: ' Casa De Repouso Recanto ')
Placeofdeath.create(name: ' Casa De Repouso Residencial Life  ')
Placeofdeath.create(name: ' Casa De Repouso Rodrigues Alves ')
Placeofdeath.create(name: ' Casa De Repouso Sant´Anna ')
Placeofdeath.create(name: ' Casa De Repouso Saude ')
Placeofdeath.create(name: ' Casa De Repouso Santa Cecilia ')
Placeofdeath.create(name: ' Casa De Repouso Santa Helena  ')
Placeofdeath.create(name: ' Casa De Repouso Styllo S/C Ltda ')
Placeofdeath.create(name: ' Casa De Repouso Tottene ')
Placeofdeath.create(name: ' Cruzada Pro-Infancia  ')
Placeofdeath.create(name: ' Casa De Saude Do Belem  ')
Placeofdeath.create(name: ' Casa De Saude N. Sra Do Bom Caminho ')
Placeofdeath.create(name: ' Casa De Saude Casa Verde  ')
Placeofdeath.create(name: ' Casa De Saude Nacional Saude  ')
Placeofdeath.create(name: ' Casa De Saude  N. Sra Do Nazareth ')
Placeofdeath.create(name: ' Casa De Saude Santana ')
Placeofdeath.create(name: ' Casa De Saude Sao Genaro  ')
Placeofdeath.create(name: ' Casa De Saude Tremembe  ')
Placeofdeath.create(name: ' Febem ')
Placeofdeath.create(name: ' Hosp. A. C. Camargo (Hosp. Do Cancer) ')
Placeofdeath.create(name: ' Hosp. A. C. Camargo - Unid Tamandare  ')
Placeofdeath.create(name: ' Hosp. Acemi ')
Placeofdeath.create(name: ' Hosp. Achiles Blosh ')
Placeofdeath.create(name: ' Hosp. Adventista De São Paulo ')
Placeofdeath.create(name: ' Hosp. Da Aeronautica  ')
Placeofdeath.create(name: ' Hosp. Agua Funda (Pam)  ')
Placeofdeath.create(name: ' Hosp. Albert. Einstein - Morumbi  ')
Placeofdeath.create(name: ' Hosp. Albert. Einstein - V.Mariana  ')
Placeofdeath.create(name: ' Hosp. Albert. Sabin ')
Placeofdeath.create(name: ' Hosp. Albert. Sabin - Imirim  ')
Placeofdeath.create(name: ' Hosp. Alivi ')
Placeofdeath.create(name: ' Hosp. Alvorada - Santo Amaro  ')
Placeofdeath.create(name: ' Hosp. Alvorada - Ibirapuera ')
Placeofdeath.create(name: ' Hosp. Alvorada - Moema  ')
Placeofdeath.create(name: ' Hosp. Ameno ')
Placeofdeath.create(name: ' Hosp. Amico (Indianopolis)  ')
Placeofdeath.create(name: ' Hosp. Amico (Saude) ')
Placeofdeath.create(name: ' Hosp. Amparo Maternal(Saude)  ')
Placeofdeath.create(name: ' Hosp. Ana Nery  ')
Placeofdeath.create(name: ' Hosp. Anchieta  ')
Placeofdeath.create(name: ' Hosp. Anglo Brasileiro  ')
Placeofdeath.create(name: ' Hosp. Atualpha Girao Rabelo (Pam) ')
Placeofdeath.create(name: ' Hosp. Auxiliar Do Coraçao ')
Placeofdeath.create(name: ' Hosp. Avicena ')
Placeofdeath.create(name: ' Hosp. Bandeirantes - Liberdade  ')
Placeofdeath.create(name: ' Hosp. Benedito Da Costa ')
Placeofdeath.create(name: ' Hosp. Benef. Portuguesa ')
Placeofdeath.create(name: ' Hosp. Bosque Da Saude ')
Placeofdeath.create(name: ' Hosp. Brigadeiro- Dr. Euclides Jesus Zerbini  ')
Placeofdeath.create(name: ' Hosp. Infantil Candido Fontoura ')
Placeofdeath.create(name: ' Hosp. Carlos Chagas ')
Placeofdeath.create(name: ' Hosp. Casa Verde  ')
Placeofdeath.create(name: ' Hosp. Castro Alves  ')
Placeofdeath.create(name: ' Hosp. Centro Ref. Saude De Mulher - Perola Biyngton ')
Placeofdeath.create(name: ' Hosp. Cidade Jardim ')
Placeofdeath.create(name: ' Hosp. Das Clinicas  ')
Placeofdeath.create(name: ' Hosp. De Clinicas Jd. Helena  ')
Placeofdeath.create(name: ' Hosp. Clinisul  ')
Placeofdeath.create(name: ' Hosp. Cometa  ')
Placeofdeath.create(name: ' Hosp. Do Coraçao  (Paraiso) ')
Placeofdeath.create(name: ' Hosp. Coraçao De Jesus  ')
Placeofdeath.create(name: ' Hosp. Auxiliar Cotoxo (Clinicas)  ')
Placeofdeath.create(name: ' Hosp. Da Criança Defeituosa ')
Placeofdeath.create(name: ' Hosp. Cruz Azul ')
Placeofdeath.create(name: ' Hosp. Cruz Verde  ')
Placeofdeath.create(name: ' Hosp. Cruz Vermelha ')
Placeofdeath.create(name: ' Hosp. Dante Pazzanese ')
Placeofdeath.create(name: ' Hosp. Infantil Darcy Vargas ')
Placeofdeath.create(name: ' Hosp. Day ')
Placeofdeath.create(name: ' Hosp. Defeitos Da Face  ')
Placeofdeath.create(name: ' Hosp. Dom Antonio De Alvarenga  ')
Placeofdeath.create(name: ' Hosp. Domini  ')
Placeofdeath.create(name: ' Hosp. Do Rim E Hipertensao  ')
Placeofdeath.create(name: ' Hosp. Dr. Augusto Gomes De Mattos ')
Placeofdeath.create(name: ' Hosp. Dr. Caetano Virgilio Netto  ')
Placeofdeath.create(name: ' Hosp. Dr. Cunha Bueno ')
Placeofdeath.create(name: ' Hosp. Dona Rosa Alves De Lima ')
Placeofdeath.create(name: ' Hosp. Prof. Dr. Zeferino Vaz  ')
Placeofdeath.create(name: ' Hosp. Emilio Ribas  ')
Placeofdeath.create(name: ' Hosp. Emilio Ribas Ii ')
Placeofdeath.create(name: ' Hosp. Eng. Armando Cintra Do Prado  ')
Placeofdeath.create(name: ' Hosp. Ermelino Matarazzo - Alipio Correa Neto ')
Placeofdeath.create(name: ' Hosp. Esperança ')
Placeofdeath.create(name: ' Hosp. Estela Maris  ')
Placeofdeath.create(name: ' Hosp. Est. Vila Alpina  ')
Placeofdeath.create(name: ' Hosp. Evaldo Foz  ')
Placeofdeath.create(name: ' Hosp. Francisco Morato De Oliveira  ')
Placeofdeath.create(name: ' Hosp. Fleming ')
Placeofdeath.create(name: ' Hosp. Gastroclinicas  ')
Placeofdeath.create(name: ' Hosp. Geral Clinicordis ')
Placeofdeath.create(name: ' Hosp. Geral Dr. Jose Pangella ')
Placeofdeath.create(name: ' Hosp. Geral Do Exercito ')
Placeofdeath.create(name: ' Hosp. Geral Do Grajau (Prof. Liberato ) ')
Placeofdeath.create(name: ' Hosp. Geral De Guaianazes ')
Placeofdeath.create(name: ' Hosp. Geral Jesus Teixeira Da Costa ')
Placeofdeath.create(name: ' Hosp. Geral De Pedreira ')
Placeofdeath.create(name: ' Hosp. Geral Da Penha  ')
Placeofdeath.create(name: ' Hosp. Geral De Sao Matheus (Manoel Bifulco) ')
Placeofdeath.create(name: ' Hosp. Geral Sao Paulo ')
Placeofdeath.create(name: ' Hosp. Geral Sapopemba ')
Placeofdeath.create(name: ' Hosp. Geral De Taipas ')
Placeofdeath.create(name: ' Hosp. Geral Alvaro Simoes De Souza  ')
Placeofdeath.create(name: ' Hosp. Geral De Vila Penteado  ')
Placeofdeath.create(name: ' Hosp. Geriatrico D. Pedro Ii  ')
Placeofdeath.create(name: ' Hosp. Geriatrico (Chac. Falgetano)  ')
Placeofdeath.create(name: ' Hosp. Gero Center ')
Placeofdeath.create(name: ' Hosp. Gloria  ')
Placeofdeath.create(name: ' Hosp. Graac - Inst. Oncologia Pediatrica  ')
Placeofdeath.create(name: ' Hosp. Heliopolis  ')
Placeofdeath.create(name: ' Hosp. Help  ')
Placeofdeath.create(name: ' Hosp. Henrique Cunha Bueno  ')
Placeofdeath.create(name: ' Hosp. Ibirapuera  ')
Placeofdeath.create(name: ' Hosp. Igesp ')
Placeofdeath.create(name: ' Hosp. Iguatemi  ')
Placeofdeath.create(name: ' Hosp. Imaculada Conceiçao ')
Placeofdeath.create(name: ' Hosp. Independencia ')
Placeofdeath.create(name: ' Hosp. Infantil Planalto ')
Placeofdeath.create(name: ' Hosp. Infantil Sabara ')
Placeofdeath.create(name: ' Hosp. Infantil Zona Norte ')
Placeofdeath.create(name: ' Hosp. Inter Placeofdeath Pari ')
Placeofdeath.create(name: ' Hosp. Interlagos  ')
Placeofdeath.create(name: ' Hosp. Ipiranga  ')
Placeofdeath.create(name: ' Hosp. Itaci ')
Placeofdeath.create(name: ' Hosp. Itacolomy ')
Placeofdeath.create(name: ' Hosp. Itamaraty- Butanta  ')
Placeofdeath.create(name: ' Hosp. Itamaraty- Jd. America  ')
Placeofdeath.create(name: ' Hosp. Itamaraty- Perdizes ')
Placeofdeath.create(name: ' Hosp. Itatiaia  ')
Placeofdeath.create(name: ' Hosp. Jaçana De Psiquiatria ')
Placeofdeath.create(name: ' Hosp. Jaragua ')
Placeofdeath.create(name: ' Hosp. Jd. Helena  ')
Placeofdeath.create(name: ' Hosp. Jd. Iva ')
Placeofdeath.create(name: ' Hosp. Jd. Sara  ')
Placeofdeath.create(name: ' Hosp. Jesus Teixeira Costa  ')
Placeofdeath.create(name: ' Hosp. Joao Paulo Ii ')
Placeofdeath.create(name: ' Hosp. Katia De Souza Rodrigues  ')
Placeofdeath.create(name: ' Hosp. Da Lapa ')
Placeofdeath.create(name: ' Hosp. Leforte ')
Placeofdeath.create(name: ' Hosp. Da Luz - Butanta  ')
Placeofdeath.create(name: ' Hosp. Da Luz - Sto. Amaro ')
Placeofdeath.create(name: ' Hosp. Da Luz - Vila Mariana ')
Placeofdeath.create(name: ' Hosp. Mandaqui  ')
Placeofdeath.create(name: ' Hosp. Mao Branca  ')
Placeofdeath.create(name: ' Hosp. Marajoara ')
Placeofdeath.create(name: ' Hosp. E Matern. Analia Franco ')
Placeofdeath.create(name: ' Hosp. E Matern. Do Bras ')
Placeofdeath.create(name: ' Hosp. E Matern. Amparo Maternal ')
Placeofdeath.create(name: ' Hosp. E Matern. Do Interlagos ')
Placeofdeath.create(name: ' Hosp. E Matern. Jardins ')
Placeofdeath.create(name: ' Hosp. E Matern. Leonor Mendes ')
Placeofdeath.create(name: ' Hosp. E Matern. Master Clinica  ')
Placeofdeath.create(name: ' Hosp. E Matern. Masterclin - Jd. Sta Adelia ')
Placeofdeath.create(name: ' Hosp. E Matern. Paranagua ')
Placeofdeath.create(name: ' Hosp. E Matern. Sacrecoeur  ')
Placeofdeath.create(name: ' Hosp. E Maternidade Santa Amalia  ')
Placeofdeath.create(name: ' Hosp. E Matern. Sao Cristovao ')
Placeofdeath.create(name: ' Hosp. E Matern. Sao Miguel  ')
Placeofdeath.create(name: ' Hosp. E Matern. Sara  ')
Placeofdeath.create(name: ' Hosp. E Matern. Santo Expedito - Itaquera ')
Placeofdeath.create(name: ' Hosp. E Maternidade V. N. Cachoeirinha  ')
Placeofdeath.create(name: ' Hosp. Mediplar  ')
Placeofdeath.create(name: ' Hosp. Infantil Menino Jesus ')
Placeofdeath.create(name: ' Hosp. Menino Jesus (Erm. Matarazzo) ')
Placeofdeath.create(name: ' Hosp. Metropolitano ')
Placeofdeath.create(name: ' Hosp. Metropolitano - Butanta ')
Placeofdeath.create(name: ' Hosp. Militar De Area De Sao Paulo  ')
Placeofdeath.create(name: ' Hosp. Militar Barro Branco  ')
Placeofdeath.create(name: ' Hosp. Mini Os. Dr. Augusto G. De Mattos ')
Placeofdeath.create(name: ' Hosp. Mini Julio Tupi ')
Placeofdeath.create(name: ' Hosp. Mini Vila Maria ')
Placeofdeath.create(name: ' Hosp. Moderno ')
Placeofdeath.create(name: ' Hosp. Monte Ararat  ')
Placeofdeath.create(name: ' Hosp. Montemagno  ')
Placeofdeath.create(name: ' Hosp. Monumento ')
Placeofdeath.create(name: ' Hosp. Moreno  ')
Placeofdeath.create(name: ' Hosp. Moura Baccini ')
Placeofdeath.create(name: ' Hosp. Mun. Prof. Alípio Correia Netto ')
Placeofdeath.create(name: ' Hosp. Mun. Arthur R. De Saboya  ')
Placeofdeath.create(name: ' Hosp. Mun. Benedito Montenegro  ')
Placeofdeath.create(name: ' Hosp. Mun. Campo Limpo  ')
Placeofdeath.create(name: ' Hosp. Mun. Cidade Tiradentes  ')
Placeofdeath.create(name: ' Hosp. Mun. Center Norte ')
Placeofdeath.create(name: ' Hosp. Mun. Dr. Alexandre Zaio - V. Nhocune  ')
Placeofdeath.create(name: ' Hosp. Mun. Dr. Jose S. Hungria  ')
Placeofdeath.create(name: ' Hosp. Mun. Ignacio Proença De Gouveia ')
Placeofdeath.create(name: ' Hosp. Mun. Itaquera ')
Placeofdeath.create(name: ' Hosp. Mun. Juceli ')
Placeofdeath.create(name: ' Hosp. Mun. Mboi Mirim Dr. Moyses Deutsch  ')
Placeofdeath.create(name: ' Hosp. Mun. Prof. Mario Degni  ')
Placeofdeath.create(name: ' Hosp. Mun. Tide Setubal ')
Placeofdeath.create(name: ' Hosp. Mun. Valdomiro De Paula ')
Placeofdeath.create(name: ' Hosp. Mun.Ver. Jose Storopoli ')
Placeofdeath.create(name: ' Hosp. Nipo Brasileiro ')
Placeofdeath.create(name: ' Hosp. Nove De Julho ')
Placeofdeath.create(name: ' Hosp. Central N. Sra Abadia ')
Placeofdeath.create(name: ' Hosp. N.Sra Da Conceiçao  ')
Placeofdeath.create(name: ' Hosp. N.Sra Das Graças  ')
Placeofdeath.create(name: ' Hosp. N.Sra Do O  ')
Placeofdeath.create(name: ' Hosp. N. Sra. De Fatima ')
Placeofdeath.create(name: ' Hosp. N. Sra. De Lourdes  ')
Placeofdeath.create(name: ' Hosp. N. Sra. Do Pari ')
Placeofdeath.create(name: ' Hosp. N. Sra. Da Penha  ')
Placeofdeath.create(name: ' Hosp. N. Sra. Do Rosario  ')
Placeofdeath.create(name: ' Hosp. N. Sra Do Sabara  ')
Placeofdeath.create(name: ' Hosp. Oito De Maio  ')
Placeofdeath.create(name: ' Hosp. Osec  ')
Placeofdeath.create(name: ' Hospedaria Aclimaçao  ')
Placeofdeath.create(name: ' Hospedaria Do Hspm  ')
Placeofdeath.create(name: ' Hosp. Infantil Promedim Ltda  ')
Placeofdeath.create(name: ' Placeofdeath João Xxiii ')
Placeofdeath.create(name: ' Placeofdeath Santo Antonio  ')
Placeofdeath.create(name: ' Placeofdeath Sta Isabel Veridiana ')
Placeofdeath.create(name: ' Placeofdeath São Jose ')
Placeofdeath.create(name: ' Placeofdeath São Luiz-Jabaquara ')
Placeofdeath.create(name: ' Hosp. N.Sra Da Abadia ')
Placeofdeath.create(name: ' Hosp. Piratininga ')
Placeofdeath.create(name: ' Hospedagem Tome De Souza  ')
Placeofdeath.create(name: ' Hosp. Alemao Oswaldo Cruz ')
Placeofdeath.create(name: ' Hosp. Panamericano  ')
Placeofdeath.create(name: ' Hosp. Paulistania ')
Placeofdeath.create(name: ' Hosp. Paulista  ')
Placeofdeath.create(name: ' Hosp. Paulistano  ')
Placeofdeath.create(name: ' Hosp. Pedreira  ')
Placeofdeath.create(name: ' Hosp. Penitenciaria Feminina  ')
Placeofdeath.create(name: ' Hosp. Personal  ')
Placeofdeath.create(name: ' Hosp. Pio Xii ')
Placeofdeath.create(name: ' Hosp. Planalto  ')
Placeofdeath.create(name: ' Hosp. Plena Saude ')
Placeofdeath.create(name: ' Hosp. Policlinica Santa Fe  ')
Placeofdeath.create(name: ' Hosp. Portinari ')
Placeofdeath.create(name: ' Hosp. Premier ')
Placeofdeath.create(name: ' Hosp. Presidente  ')
Placeofdeath.create(name: ' Hosp. Previna ')
Placeofdeath.create(name: ' Hosp. Procordis ')
Placeofdeath.create(name: ' Hosp. Procordis - Brigadeiro  ')
Placeofdeath.create(name: ' Hosp. Procordis - Carlos Sampaio  ')
Placeofdeath.create(name: ' Hosp. Prof. Edmundo Vasconcelos ')
Placeofdeath.create(name: ' Hosp. Pro-Matre Paulista  ')
Placeofdeath.create(name: ' Hosp. Prontomedi  ')
Placeofdeath.create(name: ' Hosp. Psiquiatrico - Agua Funda ')
Placeofdeath.create(name: ' Hosp. Psiquiatrico - Pinel  ')
Placeofdeath.create(name: ' Clinica Sao Genaro  ')
Placeofdeath.create(name: ' Hosp. Psiquiatrico - Vila Alpina  ')
Placeofdeath.create(name: ' Hosp. Psiquiatrico - Vila Mariana ')
Placeofdeath.create(name: ' Hosp. Regional Sul  ')
Placeofdeath.create(name: ' Hosp. Salt Lake ')
Placeofdeath.create(name: ' Hosp. Salvalus  ')
Placeofdeath.create(name: ' Hosp. Samaritano  ')
Placeofdeath.create(name: ' Hosp. Sanitas ')
Placeofdeath.create(name: ' Hosp. San Paolo ')
Placeofdeath.create(name: ' Hosp. Sta Amalia  ')
Placeofdeath.create(name: ' Hosp. Sta Angela  ')
Placeofdeath.create(name: ' Hosp. Sta Clara ')
Placeofdeath.create(name: ' Hosp. Sta Clara - Pompeia ')
Placeofdeath.create(name: ' Hosp. Santana - Dom Silverio Pimenta  ')
Placeofdeath.create(name: ' Hosp. San Vito  ')
Placeofdeath.create(name: ' Hosp. Sao Camilo - Vila Guilherme ')
Placeofdeath.create(name: ' Hosp. Sao Camilo - Ipiranga ')
Placeofdeath.create(name: ' Hosp. Sao Camilo - Pompeia  ')
Placeofdeath.create(name: ' Hosp. Sao Camilo - Santana  ')
Placeofdeath.create(name: ' Hosp. Sao Carlos  ')
Placeofdeath.create(name: ' Hosp. Sao Cristovao ')
Placeofdeath.create(name: ' Hosp. Sao Geraldo ')
Placeofdeath.create(name: ' Hosp. Sao Joao Batista  ')
Placeofdeath.create(name: ' Hosp. Sao Joaquim Da Benef. Portuguesa  ')
Placeofdeath.create(name: ' Hosp. Sao Jorge ')
Placeofdeath.create(name: ' Hosp. Sao Jose  ')
Placeofdeath.create(name: ' Hosp. Sao Jose Da Benef. Portuguesa ')
Placeofdeath.create(name: ' Hosp. Sao Leopoldo  ')
Placeofdeath.create(name: ' Hosp. Sao Lucas ')
Placeofdeath.create(name: ' Hosp. Sao Luiz Gonzaga  ')
Placeofdeath.create(name: ' Hosp. Sao Luiz - Jd.Paulista  ')
Placeofdeath.create(name: ' Hosp. Sao Luiz - Morumbi  ')
Placeofdeath.create(name: ' Hosp. Sao Luiz - Tatuape  ')
Placeofdeath.create(name: ' Hosp. Sao Marcos  ')
Placeofdeath.create(name: ' Hosp. Sao Miguel  ')
Placeofdeath.create(name: ' Hosp. Sao Paulo ')
Placeofdeath.create(name: ' Hosp. Sao Paulo - Maternidade ')
Placeofdeath.create(name: ' Hosp. Sao Rafael  ')
Placeofdeath.create(name: ' Hosp. Sao Vicente ')
Placeofdeath.create(name: ' Hosp. Estadual Sapopemba  ')
Placeofdeath.create(name: ' Hosp. Saude ')
Placeofdeath.create(name: ' Hosp. S B C - Sociedade Beneficente ')
Placeofdeath.create(name: ' Hosp. Sepaco  ')
Placeofdeath.create(name: ' Hosp. Serv. Publico Estadual  ')
Placeofdeath.create(name: ' Hosp. Serv. Publico Municipal ')
Placeofdeath.create(name: ' Hosp. Serra Mayor ')
Placeofdeath.create(name: ' Hosp. Sesi  ')
Placeofdeath.create(name: ' Hosp. S.I.M. - Serviço Ibirapuera De Saude  ')
Placeofdeath.create(name: ' Hosp. Sirio Libanes ')
Placeofdeath.create(name: ' Hosp. Sofia Marchete  ')
Placeofdeath.create(name: ' Hosp. Central Sorocabana  ')
Placeofdeath.create(name: ' Hosp. Sta. Adelaide ')
Placeofdeath.create(name: ' Hosp. Sta. Catarina ')
Placeofdeath.create(name: ' Hosp. Sta. Cecilia  ')
Placeofdeath.create(name: ' Hosp. Sta. Cruz ')
Placeofdeath.create(name: ' Hosp. Sta. Helena ')
Placeofdeath.create(name: ' Hosp. Sta. Isabel - Jaguaribe - Unid Ii ')
Placeofdeath.create(name: ' Hosp. Sta. Isabel Da Cantareira ')
Placeofdeath.create(name: ' Hosp. Sta. Joana  ')
Placeofdeath.create(name: ' Hosp. Sta. Madalena ')
Placeofdeath.create(name: ' Hosp. Sta. Maggiore - Tatuape ')
Placeofdeath.create(name: ' Hosp. Sta. Maggiore - A. Mooca - Rua Tamarataca ')
Placeofdeath.create(name: ' Hosp. Sta. Maggiore - Belenzinho  ')
Placeofdeath.create(name: ' Hosp. Sta. Maggiore - Itaim Bibi  ')
Placeofdeath.create(name: ' Hosp. Sta. Maggiore - Liberdade ')
Placeofdeath.create(name: ' Hosp. Sta. Maggiore - Mooca ')
Placeofdeath.create(name: ' Hosp. Sta. Maggiore - Paraiso ')
Placeofdeath.create(name: ' Hosp. Sta. Maggiore - Pinheiros ')
Placeofdeath.create(name: ' Hosp. Sta. Marcelina - Cid. Tiradentes  ')
Placeofdeath.create(name: ' Hosp. Sta. Marcelina - Itaim Pta. ')
Placeofdeath.create(name: ' Hosp. Sta. Marcelina - Itaquera ')
Placeofdeath.create(name: ' Hosp. Sta. Marina ')
Placeofdeath.create(name: ' Hosp. Sta. Marta  ')
Placeofdeath.create(name: ' Hosp. Sta. Paula  ')
Placeofdeath.create(name: ' Hosp. Sta. Rita ')
Placeofdeath.create(name: ' Hosp. Sta. Rosa De Lima ')
Placeofdeath.create(name: ' Hosp. Sta. Tereza De Lisieux  ')
Placeofdeath.create(name: ' Hosp. Sta. Veronica ')
Placeofdeath.create(name: ' Hosp. Sta. Virginia ')
Placeofdeath.create(name: ' Hosp. Sto. Amaro  ')
Placeofdeath.create(name: ' Hosp. Sto. Antonio  ')
Placeofdeath.create(name: ' Hosp. Sto. Antonio - Tucuruvi ')
Placeofdeath.create(name: ' Hosp. Tatuape  - Carmino Carrichio  ')
Placeofdeath.create(name: ' Hosp. Total Cor ')
Placeofdeath.create(name: ' Hosp. Unicor  ')
Placeofdeath.create(name: ' Hosp. Unicor  (Sao Gabriel) ')
Placeofdeath.create(name: ' Hosp. Unimed  ')
Placeofdeath.create(name: ' Hosp. Unisa Grajau  ')
Placeofdeath.create(name: ' Hosp. Universitario ')
Placeofdeath.create(name: ' Hosp. Valdomiro De Paula  ')
Placeofdeath.create(name: ' Hosp. Vasco Da Gama ')
Placeofdeath.create(name: ' Hosp. V. Carrao ')
Placeofdeath.create(name: ' Hosp. Vera Cruz ')
Placeofdeath.create(name: ' Hosp. E Matern. Vidas ')
Placeofdeath.create(name: ' Hosp. V. Iolanda  ')
Placeofdeath.create(name: ' Hosp. V. Lobos  ')
Placeofdeath.create(name: ' Hosp. V. Mariana  ')
Placeofdeath.create(name: ' Hosp. Vital Brasil  ')
Placeofdeath.create(name: ' Hosp. Vitoria - Unid. Tatuape ')
Placeofdeath.create(name: ' Hosp. Geral De V. N. Cachoeirinha ')
Placeofdeath.create(name: ' Hosp. V. Prudente ')
Placeofdeath.create(name: ' Hosp. Zona Norte  ')
Placeofdeath.create(name: ' Hosp. Zona Sul  ')
Placeofdeath.create(name: ' Inst. Do Cancer De São Paulo  ')
Placeofdeath.create(name: ' Incor - Inst. Do Coração - Clinicas ')
Placeofdeath.create(name: ' Inst. Arnaldo Vieira De  Carvalho ')
Placeofdeath.create(name: ' Ibcc - Inst. Bras. De Controle Ao Câncer  ')
Placeofdeath.create(name: ' Inst. Da Criança -  Prof. Pedro Alcantara ')
Placeofdeath.create(name: ' Inst. Esp. Pediatrica De S.Paulo  ')
Placeofdeath.create(name: ' Inst. De Gastroenterologia  ')
Placeofdeath.create(name: ' Inst. De Higiene Mental Sao Genaro  ')
Placeofdeath.create(name: ' Inst. Iguatemi De Clinicas  ')
Placeofdeath.create(name: ' Inst. Medico Legal - Centro ')
Placeofdeath.create(name: ' Inst. Medico Legal - Sul  ')
Placeofdeath.create(name: ' Inst. De Neuropsiquiatria De São Paulo  ')
Placeofdeath.create(name: ' Inst. De Ortopedia E Traumatologia  ')
Placeofdeath.create(name: ' Inst. De Psiquiatria Jaçana ')
Placeofdeath.create(name: ' Inst. De Psiquiatria Joy Arruda ')
Placeofdeath.create(name: ' Inst. De Psiquiatria Morumbi  ')
Placeofdeath.create(name: ' Inst. De Psiquiatria  ')
Placeofdeath.create(name: ' Inst. Santa Terezinha ')
Placeofdeath.create(name: ' Lar De Idosas Boa Esperança ')
Placeofdeath.create(name: ' Lar Corina Novelino ')
Placeofdeath.create(name: ' Lareira - Lar  Ideal Para  Sras Ltda  ')
Placeofdeath.create(name: ' Lar Nossa Sra. Da Conceiçao ')
Placeofdeath.create(name: ' Lar Nossa Sra. Das Merces ')
Placeofdeath.create(name: ' Lar Provedoria Da Comunid. Portuguesa ')
Placeofdeath.create(name: ' Lar Sta Ana Ilpi  ')
Placeofdeath.create(name: ' Lar De Repouso Sao Judas  ')
Placeofdeath.create(name: ' Lar Santa Cecilia ')
Placeofdeath.create(name: ' Lar Santo Alberto ')
Placeofdeath.create(name: ' Medic S/A - Medicina Especializada  ')
Placeofdeath.create(name: ' Mental Senior Casa De Repouso ')
Placeofdeath.create(name: ' Morada Do Sol - Casa De Repouso ')
Placeofdeath.create(name: ' Morada Primavera Casa De Repouso  ')
Placeofdeath.create(name: ' Ndt - Assist. Geriatrica Ltda ')
Placeofdeath.create(name: ' Unid. De Nefrologia E Hipertensao ')
Placeofdeath.create(name: ' Nephron Assist. Nefr S/C Ltda ')
Placeofdeath.create(name: ' Oncohemato Moderna  ')
Placeofdeath.create(name: ' Pam Agua Funda  ')
Placeofdeath.create(name: ' Pam Avenida Rudge ')
Placeofdeath.create(name: ' Pam Cidade Pedro Nunes  ')
Placeofdeath.create(name: ' Pam Cid. Tiradentes ')
Placeofdeath.create(name: ' Pam Gloria  ')
Placeofdeath.create(name: ' Pam Independencia ')
Placeofdeath.create(name: ' Pam Jd Das Oliveiras  ')
Placeofdeath.create(name: ' Pam Jd. Helena  ')
Placeofdeath.create(name: ' Pam Jd. Maia  ')
Placeofdeath.create(name: ' Pam Padre Manuel Da Nobrega ')
Placeofdeath.create(name: ' Pensionato Cantinho Da Vila ')
Placeofdeath.create(name: ' Pensionato Para Idosos Betel  ')
Placeofdeath.create(name: ' Pensionato Sao Camilo ')
Placeofdeath.create(name: ' Pensionato Para Idosos City America ')
Placeofdeath.create(name: ' Pousada Flor De Lotus Ltda  ')
Placeofdeath.create(name: ' Policlinica Itaquera  ')
Placeofdeath.create(name: ' Policlinica Sao Mateus  ')
Placeofdeath.create(name: ' Hosp. Joao Paulo I  ')
Placeofdeath.create(name: ' P.S. Abride ')
Placeofdeath.create(name: ' P.S. Andarai  ')
Placeofdeath.create(name: ' P.S. Baby Fagundes Filho  ')
Placeofdeath.create(name: ' P.S. Balneario Sao Jose ')
Placeofdeath.create(name: ' P.S. Bandeirantes ')
Placeofdeath.create(name: ' P.S. Barra Funda - Alvaro Dino De Almeida ')
Placeofdeath.create(name: ' P.S. Bresser  ')
Placeofdeath.create(name: ' P.S. Candelaria ')
Placeofdeath.create(name: ' P.S. Cangaiba ')
Placeofdeath.create(name: ' P.S. Cardiologia  ')
Placeofdeath.create(name: ' P.S. Dom Bosco  ')
Placeofdeath.create(name: ' P.S. Esplanada  ')
Placeofdeath.create(name: ' P.S. Humberto Cerrutti  ')
Placeofdeath.create(name: ' P.S. Infantil Da Agua Branca  ')
Placeofdeath.create(name: ' P.S. Infantil Sumare  ')
Placeofdeath.create(name: ' P.S. Infantil Vila Mariana  ')
Placeofdeath.create(name: ' P.S. Ipiranga ')
Placeofdeath.create(name: ' P.S. Itamaraty - Perdizes ')
Placeofdeath.create(name: ' P.S. Jabaquara  ')
Placeofdeath.create(name: ' P.S. Jd Bonfiglioli ')
Placeofdeath.create(name: ' P.S. Jd Das Flores  ')
Placeofdeath.create(name: ' P.S. Jd Sao Jorge - Butanta ')
Placeofdeath.create(name: ' P.S. Jose Sylvio De Camargo ')
Placeofdeath.create(name: ' P.S. Julio Tupy ')
Placeofdeath.create(name: ' P.S. Lapa - Joao Catarin Mezzaro  ')
Placeofdeath.create(name: ' P.S.M. 21 De Junho  ')
Placeofdeath.create(name: ' P.S. Dona. Maria Antonieta  ')
Placeofdeath.create(name: ' P.S. Maria Jose ')
Placeofdeath.create(name: ' P.S.M. Freguesia Do O ')
Placeofdeath.create(name: ' P.S. Milton Adrede  ')
Placeofdeath.create(name: ' P.S. Moema  ')
Placeofdeath.create(name: ' P.S.M. Sao Matheus  ')
Placeofdeath.create(name: ' P.S. N. Sra Das Perdizes  ')
Placeofdeath.create(name: ' P.S. Parelheiros  ')
Placeofdeath.create(name: ' P.S. Pari ')
Placeofdeath.create(name: ' P.S. Perus  ')
Placeofdeath.create(name: ' P.S. Pirituba ')
Placeofdeath.create(name: ' P.S. Pro Cardio ')
Placeofdeath.create(name: ' P.S. Santana - Lauro Ribas Braga  ')
Placeofdeath.create(name: ' P.S. Sao Jorge - Brigadeiro ')
Placeofdeath.create(name: ' P.S. Sesi - Saude ')
Placeofdeath.create(name: ' P.S. Sta. Cruz - Parelheiros  ')
Placeofdeath.create(name: ' P.S. Santo Amaro  ')
Placeofdeath.create(name: ' P.S. Tatuape- Cooper  ')
Placeofdeath.create(name: ' P.S. V. Das Merces  ')
Placeofdeath.create(name: ' P.S. Vergueiro  ')
Placeofdeath.create(name: ' P.S. V. Formosa ')
Placeofdeath.create(name: ' P.S. V. Iolanda ')
Placeofdeath.create(name: ' P.S. V. Joaniza ')
Placeofdeath.create(name: ' P.S. V. Maria ')
Placeofdeath.create(name: ' P.S. V. Penteado  ')
Placeofdeath.create(name: ' Qualita Assistencia A Saude ')
Placeofdeath.create(name: ' Recanto Do Idoso Anhanguera ')
Placeofdeath.create(name: ' Recanto Da 3ª Idade ')
Placeofdeath.create(name: ' Recanto Monte Alegre  ')
Placeofdeath.create(name: ' Recanto Sao Camilo  ')
Placeofdeath.create(name: ' Recanto Sao Camilo - Unid. Jaçana ')
Placeofdeath.create(name: ' Residencial Pro Vita  ')
Placeofdeath.create(name: ' Residencial Bem Viver ')
Placeofdeath.create(name: ' Residencial Cantinho Da Vovo  ')
Placeofdeath.create(name: ' Residencial Constantino De Souza  ')
Placeofdeath.create(name: ' Residencia Integrada Para Idosos  ')
Placeofdeath.create(name: ' Residencial Espaço Saude  ')
Placeofdeath.create(name: ' Residencial Geriatricos Ipiranga  ')
Placeofdeath.create(name: ' Residencial Otavio Tarquinio  ')
Placeofdeath.create(name: ' Residencial Parque Das Flores ')
Placeofdeath.create(name: ' Residencial Senior  ')
Placeofdeath.create(name: ' Residencial Lara Bianchi  ')
Placeofdeath.create(name: ' Sanatorio Jabaquara ')
Placeofdeath.create(name: ' Sanatorio Saint Paul Day  ')
Placeofdeath.create(name: ' Sanatorio Santa Catarina  ')
Placeofdeath.create(name: ' Sanatorio Sao Lucas ')
Placeofdeath.create(name: ' Hosp. Sta Casa De Misericordia  ')
Placeofdeath.create(name: ' Sareh - Saude E Retaguarda Placeofdeathar ')
Placeofdeath.create(name: ' Sbgg - Socied De Gerontologia Paulista  ')
Placeofdeath.create(name: ' Sedit Serv. Medicos - Mooca ')
Placeofdeath.create(name: ' Seisa - Serv. Integrados De Saude ')
Placeofdeath.create(name: ' Serv. Nefrologia De S. Paulo  ')
Placeofdeath.create(name: ' Soc. Espirita Rodrigues De Abreu  ')
Placeofdeath.create(name: ' Lar Recanto Feliz - Soc. Benef. Alema ')
Placeofdeath.create(name: ' Soc. Benef.Ass. Lar Das Maezinhas ')
Placeofdeath.create(name: ' Solar Da Vivencia - Pensionato De Idosos  ')
Placeofdeath.create(name: ' Santa Casa De Misericordia De Santo Amaro ')
Placeofdeath.create(name: ' U.B.S. - Burgo Paulista ')
Placeofdeath.create(name: ' U.B.S. - Jd. Angela ')
Placeofdeath.create(name: ' U.B.S. - Jardim Boa Vista ')
Placeofdeath.create(name: ' U.B.S. - Jd. Capela ')
Placeofdeath.create(name: ' U.B.S. - Jd. Comercial  ')
Placeofdeath.create(name: ' U.B.S. - Jardim Macedonia ')
Placeofdeath.create(name: ' U.B.S. - Jd. Mirna  ')
Placeofdeath.create(name: ' U.B.S. - Jd. Sao Luiz ')
Placeofdeath.create(name: ' U.B.S. - Mata Virgem  ')
Placeofdeath.create(name: ' U.B.S. - Vila Cisper  ')
Placeofdeath.create(name: ' Unidade Gerontologica Paulista  ')
Placeofdeath.create(name: ' Untr - Unid. De Nefr. E Transp. Renal ')


#Velorios
Funeral.create(name: 'Residência Própria')
Funeral.create(name: 'Exterior')
Funeral.create(name: 'Araçá')
Funeral.create(name: 'Campo Grande')
Funeral.create(name: 'Dom Bosco')
Funeral.create(name: 'Freguesia do Ó')
Funeral.create(name: 'Itaquera')
Funeral.create(name: 'Lajeado')
Funeral.create(name: 'Lapa')
Funeral.create(name: 'Quarta Parada')
Funeral.create(name: 'Santana')
Funeral.create(name: 'Santo Amaro')
Funeral.create(name: 'São Luiz')
Funeral.create(name: 'São Paulo')
Funeral.create(name: 'São Pedro')
Funeral.create(name: 'Saudade')
Funeral.create(name: 'Tremembé')
Funeral.create(name: 'Vila Formosa II')
Funeral.create(name: 'Vila Mariana')
Funeral.create(name: 'Vila Nova Cachoeirinha')

#Urnas
Coffin.create(name: '.ALFA-1 2,20X0,90X0,50')
Coffin.create(name: '.ALFA-2 2,10X0,70X0,50')
Coffin.create(name: '.ALFA-3 2,00x0,60x0,40')
Coffin.create(name: '.ALFA-4 1,20x0,41x0,24')
Coffin.create(name: '.ALFA-5 1,60X0,48X0,30')
Coffin.create(name: '.BETA-1  2,00X0,60X0,40')
Coffin.create(name: '.BETA-2  2,00X0,70X0,50')
Coffin.create(name: '.BETA-3  2,10X0,60X0,40')
Coffin.create(name: '.BETA-4  2,10X0,70X0,50')
Coffin.create(name: '.C-1  2,00X0,60X0,40')
Coffin.create(name: '.C-3  2,10X0,70X0,50')
Coffin.create(name: '.C-4  2,00X0,70X0,50')
Coffin.create(name: '.C-6  1,90X0,60X0,40')
Coffin.create(name: '.CJ. NAC. INFANTIL (NC2) 1,20X0,41X0,24')
Coffin.create(name: '.CJ. NAC. INFANTIL (NC3)1,60X0,48X0,30')
Coffin.create(name: '.CJ. NAC. INTANTIL (NC1) 0,80X0,31X0,21')
Coffin.create(name: '.CJ. NAC. OURO (NA1) 2,00X0,60X0,40')
Coffin.create(name: '.CJ. NAC. OURO (NA2) 2,10X0,70X0,50')
Coffin.create(name: '.CJ. NAC. OURO (NA3) 2,20X0,70X0,50')
Coffin.create(name: '.CJ. NAC. OURO (NA4) 2,10X0,60X0,40')
Coffin.create(name: '.CJ. NAC. PRATA (NB4) 2,00X0,60X0,40')
Coffin.create(name: '.CJ. NAC. PRATA (NB5) 2,10X0,70X0,50')
Coffin.create(name: '.CJ.INT. INFANTIL (IC10) 1,20X0,41X0,24')
Coffin.create(name: '.CJ.INT. INFANTIL (IC3) 1,60X0,48X0,30')
Coffin.create(name: '.CJ.INT. INFANTIL (IC4) 0,80X0,31X0,21')
Coffin.create(name: '.CJ.INT. OURO (IA1) 2,20X0,70X0,50')
Coffin.create(name: '.CJ.INT. OURO (IA2) 2,00X0,60X0,40')
Coffin.create(name: '.CJ.INT. OURO (IA3) 2,10X0,70X0,50')
Coffin.create(name: '.CJ.INT. PRATA (IB2) 2,20X0,70X0,50')
Coffin.create(name: '.CJ.INT. PRATA (IB5) 2,00X0,60X0,40')
Coffin.create(name: '.CJ.INT. PRATA (IB6) 1,90X0,60X0,40')
Coffin.create(name: '.CJ.INT. PRATA (IB7) 2,00X0,70X0,50')
Coffin.create(name: '.CJ.INT. PRATA (IB8) 2,10X0,60X0,40')
Coffin.create(name: '.CJ.INT. PRATA (IB9) 2,10X0,70X0,50')
Coffin.create(name: '.CONJ.INT. PRATA (IB1) 2,20X0,90X0,50')
Coffin.create(name: '.D-1  2,00X0,60X0,40')
Coffin.create(name: '.D-3  2,10X0,70X0,50')
Coffin.create(name: '.D-4  2,00X0,70X0,50')
Coffin.create(name: '.D-6 1,90X0,60X0,40')
Coffin.create(name: '.E-1 2,00X0,60X0,40')
Coffin.create(name: '.E-2 2,10X0,70X0,50')
Coffin.create(name: '.E-3 1,90X0,60X0,40')
Coffin.create(name: '.E-4 2,10X0,60X0,4.0')
Coffin.create(name: '.F-1 2,10X0,60X0,40')
Coffin.create(name: '.F-3  2,10X0,70X0,50')
Coffin.create(name: '.F-4  1,90X0,60X0,40')
Coffin.create(name: '.F-5 2,00X0,70X0,50')
Coffin.create(name: '.H-1  2,00X0,60X0,40')
Coffin.create(name: '.H-2  2,10X0,70X0,50')
Coffin.create(name: '.H-3  1,90X0,60X0,40')
Coffin.create(name: '.H-5 2,00X0,70X0,50')
Coffin.create(name: '.I-1  2,00X0,60X0,40')
Coffin.create(name: '.I-2  2,10X0,70X0,50')
Coffin.create(name: '.I-3  1,90X0,60X0,40')
Coffin.create(name: '.I-5   2,00x0,70x0,50')
Coffin.create(name: '.J-1. 2,00X0,60X0,40')
Coffin.create(name: '.J-2  2,10X0,70X0,50')
Coffin.create(name: '.J-4  1,90X0,60X0,40')
Coffin.create(name: '.J-5 2,00X0,70X0,50')
Coffin.create(name: '.K-1 2,00X0,60X0,40')
Coffin.create(name: '.K-10 2,20X1,00X0,90')
Coffin.create(name: '.K-2  2,10X0,60X0,40')
Coffin.create(name: '.K-3  2,10X0,70X0,50')
Coffin.create(name: '.K-5  1,90X0,60X0,40')
Coffin.create(name: '.K-7  2,00X0,70X0,50')
Coffin.create(name: '.K-8 2,10X0,90X0,50')
Coffin.create(name: '.K-9 2,20X0,70X0,50')
Coffin.create(name: '.L-1  2,00X0,60X0,40')
Coffin.create(name: '.L-2  2,10X0,70X0,50')
Coffin.create(name: '.L-4  1,90X0,60X0,40')
Coffin.create(name: '.L-5  2,10X0,60X0,40')
Coffin.create(name: '.L-6 2,00X0,70X0,50')
Coffin.create(name: '.L-7 2,10X0,90X0,50')
Coffin.create(name: '.L-8 2,20X0,90X0,50')
Coffin.create(name: '.L-9 2,20X1,00X0,90')
Coffin.create(name: '.M-1 2,00X0,60X0,40')
Coffin.create(name: '.M-2 2,10X0,60X0,40')
Coffin.create(name: '.M-3 2,10X0,70X0,50')
Coffin.create(name: '.M-4 2,20X0,60X0,40')
Coffin.create(name: '.M-5 1,90X0,60X0,40')
Coffin.create(name: '.M-5 2,20X0,90X0,50')
Coffin.create(name: '.M-7 2,00X0,70X0,50')
Coffin.create(name: '.N-1 2,20X0,90X0,50')
Coffin.create(name: '.N-2 2,10X0,70X0,50')
Coffin.create(name: '.N-3 2,00X0,60X0,40')
Coffin.create(name: '.N-4 1,60X0,48X0,30')
Coffin.create(name: '.N-5 1,20X0,41X0,24')
Coffin.create(name: '.N-6  0,80X0,31X0,21')
Coffin.create(name: '.N-7 1,90X0,60X0,40')
Coffin.create(name: '.O-2  1,60X0,48X0,30')
Coffin.create(name: '.O-3  1,20X0,41X0,24')
Coffin.create(name: '.O-4  0,80X0,31X0,21')
Coffin.create(name: '.O-5 0,60X0,26X0,21')
Coffin.create(name: '.OMEGA-1 1,90x0,60x0,40')
Coffin.create(name: '.OMEGA-2 2,00x0,60x0,40')
Coffin.create(name: '.OMEGA-3 2,00x0,70x0,50')
Coffin.create(name: '.OMEGA-4 2,10x0,60x0,40')
Coffin.create(name: '.Q-2 1,60X0,52X0,28')
Coffin.create(name: '.Q-3 1,20X0,42X0,23')
Coffin.create(name: '.Q-4 0,80X0,31X0,21')
Coffin.create(name: '.Q-5 0,60X0,26X0,20')
Coffin.create(name: '.R-2  0,80X0,31X0,21')
Coffin.create(name: '.R-6 1,20X0,41X0,24')
Coffin.create(name: '.U-1 2,00X0,60X0,40')
Coffin.create(name: '.U-2 2,10X0,60X0,40')
Coffin.create(name: '.U-3 2,10X0,70X0,50')
Coffin.create(name: '.U-4 2,10X0,90X0,50')
Coffin.create(name: '.U-5 2,20X0,70X0,50')
Coffin.create(name: '.U-6  2,20X1,00X0,90')
Coffin.create(name: '.U-7 2,00X0,70X0,50')
Coffin.create(name: '.U-7 2,00X0,70X0,50')
Coffin.create(name: '.U-8 1,90X0,60X0,40')
Coffin.create(name: '.URNA NACIONAL INFANTIL')
Coffin.create(name: '.V-1  2,00X0,60X0,40')
Coffin.create(name: '.V-3  2,10X0,70X0,50')
Coffin.create(name: '.V-4  1,90X0,60X0,40')
Coffin.create(name: '.V-5 2,00X0,70X0,50')
Coffin.create(name: '.Y-1  1,60X0,48X0,30')
Coffin.create(name: '.Y-2  1,20X0,41X0,24')
Coffin.create(name: '.Y-3  0,80X0,31X0,21')
Coffin.create(name: '.Y-4  0,60X0,26X0,21')
Coffin.create(name: '.Z-1  2,00X0,60X0,40')
Coffin.create(name: '.Z-2  2,10X0,60X0,40')
Coffin.create(name: '.Z-3 2,10X0,70X0,50')
Coffin.create(name: '.Z-4  2,20X0,60X0,40')
Coffin.create(name: '.Z-5  1,90X0,60X0,40')
Coffin.create(name: '.Z-6 2,00X0,70X0,50')



